### ISSUE TITLE
Allocation of 5224220000 exceeds 10% of system memory.

### ISSUE THREAD

**Issue by zysNLP** [layer6ai-labs/DropoutNet#3]
When I execute main.py, I get：Allocation of 5224220000 exceeds 10% of system memory.
Why?

**Comment by ninesky110** [comment]
I have the same problem, have you solved it？

**Comment by ninesky110** [comment]
![image](https://user-images.githubusercontent.com/38121533/125430018-8653c451-aa72-487e-9b0f-f51d069e00c6.png)

**Comment by ninesky110** [comment]
when I changed the "data_batch_size" or "max_data_per_step"，I got the error.
![image](https://user-images.githubusercontent.com/38121533/125432414-d9a4cfb0-a97a-46b4-b4c5-4dab9ada8889.png)

**Comment by guangster** [comment]
How much RAM do you have on the machine where you are running this code? Also how much GPU memory? In our experiments we saw RAM go up to about 30GB and we used a GPU with 12GB of memory.

@ninesky110 It looks like your loss blew up: https://github.com/layer6ai-labs/DropoutNet/blob/master/main.py#L164-L166. Regarding changing data_batch_size, we recommend using the suggested parameters. If you would like to try different parameters like reduced batch sizes, you may have to tune the hypers a bit.
